split to 2 scripts

diff --git a/scripts/connect b/scripts/connect
--- a/scripts/connect
+++ b/scripts/connect
@@ -1,49 +1,27 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
-set -e
+set -e -o nounset
 
-urlencode() {
+if test $# -ge 1 && test -x "$(which $1 2>&-)" ; then
+  exec "$@"
+elif test $# -ge 1 ; then
+  echo "=== [$0] err: command not found: $1 (full command: $@)"
+  exit 1
+elif ps -ef | egrep -v 'grep|openvpn.sh' | grep -q openvpn ; then
+  echo "=== [$0] inf: service already running, please restart container to apply changes"
+  exit 0
+fi
 
-  local save_LC=$LC_COLLATE
-  LC_COLLATE=C
-
-  local i
-  local length="${#1}"
-
-  for i in $(seq 0 $((length-1))); do
-     local c=${1:$i:1}
-     case "$c" in
-        [a-zA-Z0-9/_.~-] ) printf '%s' "$c" ;;
-        * ) printf '%%%02X' "'$c" ;;
-     esac
-  done
-
-  LC_COLLATE=$save_LC
-}
-
-wait_file() {
-  local file="$1"; shift
-  local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout
-
-  echo "=== log: waiting fo file: $file"
-
-  until test $((wait_seconds-=5)) -le 0 -o -f "$file" ; do
-    echo ">> $wait_seconds ... sleep 5"
-    sleep 5
-  done
-}
-
-SAML_USER=${SAML_USER:-testuser@example.org}
-SAML_PASS=${SAML_PASS:-testuser_password}
-
-OVPN_CONF=${OVPN_CONF:-./ovpn.conf}
-test -f ${OVPN_CONF} || { echo "=== err: openvpn config file (${OVPN_CONF}) doesn't exist" ; exit 1 ; }
+test -f ${OVPN_CONF} || { echo "=== [$0] err: file defined by passed variable OVPN_CONF (${OVPN_CONF}) doesn't exist" ; exit 1 ; }
+touch ${RESP_FILE} 2>&- || { echo "=== [$0] err: cannot touch file defined by passed variable RESP_FILE (${RESP_FILE}) doesn't exist" ; exit 1 ; }
+test -n "${SAML_USER}" || { echo "=== [$0] err: passed variable SAML_USER is empty" ; exit 1 ; }
+test -n "${SAML_PASS}" || { echo "=== [$0] err: passed variable SAML_USER is empty" ; exit 1 ; }
 
 HOST=$(cat ${OVPN_CONF} | grep ^remote | head -n1 | cut -d" " -f2)
 PORT=$(cat ${OVPN_CONF} | grep ^remote | head -n1 | cut -d" " -f3)
 PROTO=$(cat ${OVPN_CONF} | grep ^proto | head -n1 | cut -d" " -f2)
 RAND=$(openssl rand -hex 12)
-SRV=$(dig a +short "${RAND}.${HOST}" | head -n1)
+IP=$(dig a +short "${RAND}.${HOST}" | head -n1)
 
 sed \
     -e '/^proto .*/d' \
@@ -53,54 +31,55 @@ sed \
     -e '/^auth-user-pass.*/d' \
     -e '/^auth-federate.*/d' \
     -e '/^auth-retry interact.*/d' \
-    -e '/^nobind.*/a persist-key\npersist-tun' \
-    ${OVPN_CONF} > ${OVPN_CONF}-${SRV}
+    -e '/^nobind.*/a persist-key\npersist-tun\ntls-client\nresolv-retry 30\nkeepalive 10 60' \
+    ${OVPN_CONF} > ${OVPN_CONF}-${IP}
 
-echo "=== log: getting init SAML request..."
-OVPN_OUT=$(openvpn --config "${OVPN_CONF}-${SRV}" \
-  --proto "$PROTO" --remote "${SRV}" "${PORT}" \
-  --auth-user-pass <( printf "%s\n%s\n" "N/A" "ACS::35001" ) 2>&1 | grep AUTH_FAILED,CRV1)
+#   -e '/^nobind.*/a persist-key\npersist-tun\ntls-client\nresolv-retry 30\nkeepalive 10 60\ncompress lz4' \
 
-URL=$(echo "$OVPN_OUT" | grep -Eo 'https://.+')
-test -n ${URL} || { echo "=== err: returned from init openvpn connect SAML request URL is empty" ; exit 1 ; }
-
-SID=$(echo "$OVPN_OUT" | awk -F : '{print $7}')
-test -n ${SID} || { echo "=== err: returned from init openvpn connect SID is empty" ; exit 1 ; }
-
-# Delete stale SAML files
-RESP_FILE=${RESP_FILE:-./resp.txt}
-rm -f ${RESP_FILE} ${RESP_FILE}.cred
-
-rm -fr ${HOME}/.saml2aws
-rm -fr saml-response.b64
-
-S2A_LOG=${S2A_LOG:-./saml2aws.log}
-rm -f ${S2A_LOG}
-
-echo "=== log: getting SAML response..."
-
-echo "=== log: saml2aws configure" >> ${S2A_LOG} 2>&1
-saml2aws configure --skip-prompt --idp-account='clientvpn-jumpcloud' --idp-provider='JumpCloud' --mfa='Auto' --url=${URL} >> ${S2A_LOG} 2>&1
-echo "=== log: saml2aws login" >> ${S2A_LOG} 2>&1
-saml2aws login -a clientvpn-jumpcloud --username=${SAML_USER} --password=${SAML_PASS} --cache-saml --cache-file=saml-response.b64 --aws-urn='urn:amazon:webservices:clientvpn' --skip-prompt >> ${S2A_LOG} 2>&1 || true
-
-! grep -q -i "Response did not contain a valid SAML assertion" ${S2A_LOG} || { 
-  echo "=== err: SAML authentication failed, please check your username and/or password"
+echo "=== [$0] log: getting SAML request..."
+/app/getauth ${IP} ${PROTO} ${PORT} ${SAML_USER} ${SAML_PASS} ${OVPN_CONF} ${RESP_FILE} || { 
+  echo "=== [$0] err: script /app/get-auth failed with code $?"
   exit 1
 }
 
-test -f saml-response.b64 || { echo "=== err: saml2aws didn't create cache-file ('saml-response.b64')" ; exit 1 ; }
-urlencode $(cat saml-response.b64) > saml-response.urlencoded
-cp saml-response.urlencoded ${RESP_FILE}
+test -s ${RESP_FILE}.cred || { echo "=== [$0] err: received SAML response file doesn't exist or empty" ; exit 1 ; }
 
-wait_file ${RESP_FILE} 300
-test -f ${RESP_FILE} || { echo "=== err: getting SAML response file time out"; exit 1 ; }
+ovpn_args=(
+  "--config" "${OVPN_CONF}-${IP}"
+  "--proto" "$PROTO"
+  "--remote" "${IP}" "${PORT}"
+  "--script-security" "2"
+  "--inactive" "3600"
+  "--down" "'/app/getauth ${IP} ${PROTO} ${PORT} ${SAML_USER} ${SAML_PASS} ${OVPN_CONF} ${RESP_FILE}'"
+  "--up-restart"
+  "--auth-user-pass" "${RESP_FILE}.cred"
+)
 
-printf "%s\n%s\n" "N/A" "CRV1::${SID}::$(cat ${RESP_FILE})" > ${RESP_FILE}.cred
-chmod 600 ${RESP_FILE}.cred
+# "--route-up" "/usr/bin/env rm -f ${RESP_FILE} ${RESP_FILE}.cred"
+# "--up" "/usr/bin/env rm -f ${RESP_FILE} ${RESP_FILE}.cred"
 
-echo "=== log: running OpenVPN"
-sh -c "openvpn --config ${OVPN_CONF}-${SRV} --inactive 3600 \
-  --proto $PROTO --remote ${SRV} ${PORT} \
-  --script-security 2 --route-up '/usr/bin/env rm -f ${RESP_FILE} ${RESP_FILE}.cred' \
-  --auth-user-pass ${RESP_FILE}.cred"
+test "${DNS:-true}" != "true" || { 
+  echo "=== [$0] log: using server-side DNS"
+  ovpn_args+=(
+    "--route-up" "/etc/openvpn/client.up"
+    "--route-pre-down" "/etc/openvpn/client.down"
+  )
+}
+
+! test -n "${MSS:-}" -a "${PROTO}" = "udp" || { 
+  echo "=== [$0] log: set internal datagram fragmentation to: $MSS"
+  ovpn_args+=(
+    "--fragment $MSS --mssfix"
+  )
+}
+
+! grep -Eq "^[0-9]+$" <(echo "${GROUPID:-}") || {
+  echo "=== [$0] log: GID for 'vpn' group is chnaged to ${GROUPID}"
+  groupmod -g ${GROUPID} -o vpn
+}
+
+mkdir -p /dev/net
+test -c /dev/net/tun || mknod -m 0666 /dev/net/tun c 10 200
+echo "=== [$0] log: running openvpn client"
+set -x
+exec sg vpn -c "openvpn ${ovpn_args[*]}"
